# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/design_1_axi_noc_1_0.xci
# IP: The module: 'design_1_axi_noc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/bd_4bb4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4bb4 || ORIG_REF_NAME==bd_4bb4} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/bd_4bb4_S00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4bb4_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_4bb4_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_1/bd_4bb4_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4bb4_const_0_0 || ORIG_REF_NAME==bd_4bb4_const_0_0} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_2/bd_4bb4_M00_AXI_nsu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4bb4_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_4bb4_M00_AXI_nsu_0} -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/xdc/bd_4bb4_S00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4bb4_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_4bb4_S00_AXI_nmu_0} -quiet] {/bd_4bb4_S00_AXI_nmu_0_top_INST } ]/bd_4bb4_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_2/xdc/bd_4bb4_M00_AXI_nsu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4bb4_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_4bb4_M00_AXI_nsu_0} -quiet] {/bd_4bb4_M00_AXI_nsu_0_top_INST } ]/bd_4bb4_M00_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/design_1_axi_noc_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/design_1_axi_noc_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/design_1_axi_noc_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/design_1_axi_noc_1_0.xci
# IP: The module: 'design_1_axi_noc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/bd_4bb4.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4bb4 || ORIG_REF_NAME==bd_4bb4} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/bd_4bb4_S00_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4bb4_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_4bb4_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_1/bd_4bb4_const_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4bb4_const_0_0 || ORIG_REF_NAME==bd_4bb4_const_0_0} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_2/bd_4bb4_M00_AXI_nsu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_4bb4_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_4bb4_M00_AXI_nsu_0} -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/xdc/bd_4bb4_S00_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4bb4_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_4bb4_S00_AXI_nmu_0} -quiet] {/bd_4bb4_S00_AXI_nmu_0_top_INST } ]/bd_4bb4_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_2/xdc/bd_4bb4_M00_AXI_nsu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_4bb4_M00_AXI_nsu_0 || ORIG_REF_NAME==bd_4bb4_M00_AXI_nsu_0} -quiet] {/bd_4bb4_M00_AXI_nsu_0_top_INST } ]/bd_4bb4_M00_AXI_nsu_0_top_INST ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/design_1_axi_noc_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/design_1_axi_noc_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/design_1_axi_noc_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_noc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
