# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.srcs/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_2/Ajit_vck190_axi_uartlite_0_2.xci
# IP: The module: 'Ajit_vck190_axi_uartlite_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_2/Ajit_vck190_axi_uartlite_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_2/Ajit_vck190_axi_uartlite_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_2/Ajit_vck190_axi_uartlite_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.srcs/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_2/Ajit_vck190_axi_uartlite_0_2.xci
# IP: The module: 'Ajit_vck190_axi_uartlite_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_2/Ajit_vck190_axi_uartlite_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_2/Ajit_vck190_axi_uartlite_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_2/Ajit_vck190_axi_uartlite_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
