# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.srcs/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/Ajit_vck190_axi_uartlite_1_smc_0.xci
# IP: The module: 'Ajit_vck190_axi_uartlite_1_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/bd_5f6e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_5/bd_5f6e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_11/bd_5f6e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_13/bd_5f6e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_14/bd_5f6e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_15/bd_5f6e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_16/bd_5f6e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_17/bd_5f6e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_18/bd_5f6e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_19/bd_5f6e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_20/bd_5f6e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_21/bd_5f6e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_22/bd_5f6e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_23/bd_5f6e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_11/bd_5f6e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_11/bd_5f6e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_16/bd_5f6e_s00a2s_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_17/bd_5f6e_sarn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_17/bd_5f6e_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_18/bd_5f6e_srn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_18/bd_5f6e_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_19/bd_5f6e_sawn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_19/bd_5f6e_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_20/bd_5f6e_swn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_20/bd_5f6e_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_21/bd_5f6e_sbn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_21/bd_5f6e_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_22/bd_5f6e_m00s2a_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_1_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_1_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.srcs/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/Ajit_vck190_axi_uartlite_1_smc_0.xci
# IP: The module: 'Ajit_vck190_axi_uartlite_1_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/bd_5f6e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_5/bd_5f6e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_11/bd_5f6e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_13/bd_5f6e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_14/bd_5f6e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_15/bd_5f6e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_16/bd_5f6e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_17/bd_5f6e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_18/bd_5f6e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_19/bd_5f6e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_20/bd_5f6e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_21/bd_5f6e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_22/bd_5f6e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_23/bd_5f6e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_11/bd_5f6e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_11/bd_5f6e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_16/bd_5f6e_s00a2s_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_17/bd_5f6e_sarn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_17/bd_5f6e_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_18/bd_5f6e_srn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_18/bd_5f6e_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_19/bd_5f6e_sawn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_19/bd_5f6e_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_20/bd_5f6e_swn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_20/bd_5f6e_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_21/bd_5f6e_sbn_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_21/bd_5f6e_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/bd_0/ip/ip_22/bd_5f6e_m00s2a_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_1_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ajit_vck190_axi_uartlite_1_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
