transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/xil_defaultlib
vlib riviera/smartconnect_v1_0
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_register_slice_v2_1_29
vlib riviera/axi_vip_v1_1_15
vlib riviera/lib_cdc_v1_0_2
vlib riviera/proc_sys_reset_v5_0_14
vlib riviera/xlconstant_v1_1_8
vlib riviera/lib_pkg_v1_0_3
vlib riviera/axi_apb_bridge_v3_0_19
vlib riviera/versal_cips_ps_vip_v1_0_7
vlib riviera/cpm4_v1_0_14
vlib riviera/cpm5_v1_0_14
vlib riviera/axi_lite_ipif_v3_0_4
vlib riviera/lib_srl_fifo_v1_0_3
vlib riviera/axi_uartlite_v2_0_33
vlib riviera/noc_nsu_v1_0_0

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap xil_defaultlib riviera/xil_defaultlib
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_29 riviera/axi_register_slice_v2_1_29
vmap axi_vip_v1_1_15 riviera/axi_vip_v1_1_15
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_14 riviera/proc_sys_reset_v5_0_14
vmap xlconstant_v1_1_8 riviera/xlconstant_v1_1_8
vmap lib_pkg_v1_0_3 riviera/lib_pkg_v1_0_3
vmap axi_apb_bridge_v3_0_19 riviera/axi_apb_bridge_v3_0_19
vmap versal_cips_ps_vip_v1_0_7 riviera/versal_cips_ps_vip_v1_0_7
vmap cpm4_v1_0_14 riviera/cpm4_v1_0_14
vmap cpm5_v1_0_14 riviera/cpm5_v1_0_14
vmap axi_lite_ipif_v3_0_4 riviera/axi_lite_ipif_v3_0_4
vmap lib_srl_fifo_v1_0_3 riviera/lib_srl_fifo_v1_0_3
vmap axi_uartlite_v2_0_33 riviera/axi_uartlite_v2_0_33
vmap noc_nsu_v1_0_0 riviera/noc_nsu_v1_0_0

vlog -work xilinx_vip  -incr "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"/home/iitg/VivadoFull/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \

vcom -work xpm -93  -incr \
"/home/iitg/VivadoFull/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_fpga_top_0_0/sim/design_1_fpga_top_0_0.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/c6b2/hdl/sc_mmu_v1_0_vl_rfs.sv" \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/abb8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/7827/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/sc_node_v1_0_vl_rfs.sv" \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/bd53/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/79ce/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/ebf7/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/6eea/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_29  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_15  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \

vcom -work lib_cdc_v1_0_2 -93  -incr \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_14 -93  -incr \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vlog -work xlconstant_v1_1_8  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v" \

vcom -work lib_pkg_v1_0_3 -93  -incr \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work axi_apb_bridge_v3_0_19 -93  -incr \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/41ea/hdl/axi_apb_bridge_v3_0_vh_rfs.vhd" \

vcom -work versal_cips_ps_vip_v1_0_7 -93  -incr \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl/versal_cips_ps_vip_v1_0_rfs.vhd" \

vlog -work versal_cips_ps_vip_v1_0_7  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl/versal_cips_ps_vip_v1_0_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/ip_0/sim/versal_cips_ps_vip_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/hdl/pspmc_v1_4_0_sim.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/sim/bd_70da_pspmc_0_0.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/sim/bd_70da.v" \

vlog -work cpm4_v1_0_14  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/cpm4_v1_0_vl_rfs.sv" \

vlog -work cpm5_v1_0_14  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/cpm5_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/sim/design_1_versal_cips_0_0.sv" \

vcom -work axi_lite_ipif_v3_0_4 -93  -incr \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_3 -93  -incr \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_uartlite_v2_0_33 -93  -incr \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/df48/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_0/sim/design_1_axi_uartlite_0_0.vhd" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_0/sim/design_1_axi_uartlite_1_0.vhd" \
"../../../bd/design_1/ip/design_1_rst_versal_cips_0_99M_1/sim/design_1_rst_versal_cips_0_99M_1.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/sim/bd_c482.v" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_0/sim/bd_c482_one_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_1/sim/bd_c482_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_2/sim/bd_c482_s00mmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_3/sim/bd_c482_s00tr_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_4/sim/bd_c482_s00sic_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_5/sim/bd_c482_s00a2s_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_6/sim/bd_c482_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_7/sim/bd_c482_srn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_8/sim/bd_c482_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_9/sim/bd_c482_swn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_10/sim/bd_c482_sbn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_11/sim/bd_c482_m00s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/bd_0/ip/ip_12/sim/bd_c482_m00e_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_uartlite_0_smc_1/sim/design_1_axi_uartlite_0_smc_1.v" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/sim/bd_05d2.v" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_0/sim/bd_05d2_one_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_1/sim/bd_05d2_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_2/sim/bd_05d2_s00mmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_3/sim/bd_05d2_s00tr_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_4/sim/bd_05d2_s00sic_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_5/sim/bd_05d2_s00a2s_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_6/sim/bd_05d2_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_7/sim/bd_05d2_srn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_8/sim/bd_05d2_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_9/sim/bd_05d2_swn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_10/sim/bd_05d2_sbn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_11/sim/bd_05d2_m00s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/bd_0/ip/ip_12/sim/bd_05d2_m00e_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_uartlite_1_smc_2/sim/design_1_axi_uartlite_1_smc_2.v" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/sim/bd_4b24.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/noc_nmu_v1_0_vl_rfs.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm/bd_4b24_S00_AXI_nmu_0_top.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm/NOC_NMU512_SPP.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm/bd_4b24_S00_AXI_nmu_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_1/sim/bd_4b24_const_0_0.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_2/hdl/bfm/bd_4b24_M00_AXI_nsu_0_top.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_2/hdl/bfm/NOC_NSU512_SPP.v" \

vlog -work noc_nsu_v1_0_0  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/noc_nsu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_2/hdl/bfm/bd_4b24_M00_AXI_nsu_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/sim/design_1_axi_noc_0_1.v" \
"../../../bd/design_1/ip/design_1_axi_noc_1_0/bd_0/sim/bd_4bb4.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm/bd_4bb4_S00_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm/bd_4bb4_S00_AXI_nmu_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_1/sim/bd_4bb4_const_0_0.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_2/hdl/bfm/bd_4bb4_M00_AXI_nsu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_2/hdl/bfm/bd_4bb4_M00_AXI_nsu_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/57d2/hdl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/2b00/ttcl" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/624a/hdl/verilog" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/869c/hdl/verilog" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ipshared/342d/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm" "+incdir+../../../../project_1.gen/sources_1/bd/design_1/ip/design_1_axi_noc_1_0/bd_0/ip/ip_0/hdl/bfm" "+incdir+/home/iitg/VivadoFull/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_29 -l axi_vip_v1_1_15 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l lib_pkg_v1_0_3 -l axi_apb_bridge_v3_0_19 -l versal_cips_ps_vip_v1_0_7 -l cpm4_v1_0_14 -l cpm5_v1_0_14 -l axi_lite_ipif_v3_0_4 -l lib_srl_fifo_v1_0_3 -l axi_uartlite_v2_0_33 -l noc_nsu_v1_0_0 \
"../../../bd/design_1/ip/design_1_axi_noc_1_0/sim/design_1_axi_noc_1_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/sim/design_1.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

