set_property SRC_FILE_INFO {cfile:/home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/constraints/constraints.xdc rfile:../../constraints/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN G37         [get_ports {reset_clk_0}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN G36         [get_ports {reset_0}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L35 [get_ports {CPU_MODE_0[1]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K36 [get_ports {CPU_MODE_0[0]}]
