set_property SRC_FILE_INFO {cfile:/home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/constraints/constraints.xdc rfile:../../constraints/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE42 [get_ports {clk_p}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF43 [get_ports {clk_n}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN G37         [get_ports {reset_clk}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN G36         [get_ports {reset}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  C17   [get_ports {DEBUG_UART_TX}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {DEBUG_UART_RX}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L35 [get_ports {CPU_MODE[1]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K36 [get_ports {CPU_MODE[0]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN L33         [get_ports {SERIAL_UART_RX}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property    PACKAGE_PIN K33         [get_ports {SERIAL_UART_TX}]
