# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/Ajit_vck190/Ajit_vck190.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190 || ORIG_REF_NAME==Ajit_vck190} -quiet] -quiet

# IP: bd/Ajit_vck190/ip/Ajit_vck190_fpga_top_0_1/Ajit_vck190_fpga_top_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190_fpga_top_0_1 || ORIG_REF_NAME==Ajit_vck190_fpga_top_0_1} -quiet] -quiet

# IP: bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_2/Ajit_vck190_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190_axi_uartlite_0_2 || ORIG_REF_NAME==Ajit_vck190_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_2/Ajit_vck190_axi_uartlite_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190_axi_uartlite_1_2 || ORIG_REF_NAME==Ajit_vck190_axi_uartlite_1_2} -quiet] -quiet

# IP: bd/Ajit_vck190/ip/Ajit_vck190_versal_cips_0_3/Ajit_vck190_versal_cips_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190_versal_cips_0_3 || ORIG_REF_NAME==Ajit_vck190_versal_cips_0_3} -quiet] -quiet

# Block Designs: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_versal_cips_0_3/bd_0/bd_98bc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_98bc || ORIG_REF_NAME==bd_98bc} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_versal_cips_0_3/bd_0/ip/ip_0/bd_98bc_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_98bc_pspmc_0_0 || ORIG_REF_NAME==bd_98bc_pspmc_0_0} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_versal_cips_0_3/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: bd/Ajit_vck190/ip/Ajit_vck190_rst_versal_cips_0_79M_3/Ajit_vck190_rst_versal_cips_0_79M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190_rst_versal_cips_0_79M_3 || ORIG_REF_NAME==Ajit_vck190_rst_versal_cips_0_79M_3} -quiet] -quiet

# IP: bd/Ajit_vck190/ip/Ajit_vck190_mynoc_0/Ajit_vck190_mynoc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190_mynoc_0 || ORIG_REF_NAME==Ajit_vck190_mynoc_0} -quiet] -quiet

# IP: bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_0_smc_0/Ajit_vck190_axi_uartlite_0_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190_axi_uartlite_0_smc_0 || ORIG_REF_NAME==Ajit_vck190_axi_uartlite_0_smc_0} -quiet] -quiet

# IP: bd/Ajit_vck190/ip/Ajit_vck190_axi_uartlite_1_smc_0/Ajit_vck190_axi_uartlite_1_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190_axi_uartlite_1_smc_0 || ORIG_REF_NAME==Ajit_vck190_axi_uartlite_1_smc_0} -quiet] -quiet

# IP: bd/Ajit_vck190/ip/Ajit_vck190_mynoc_1/Ajit_vck190_mynoc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Ajit_vck190_mynoc_1 || ORIG_REF_NAME==Ajit_vck190_mynoc_1} -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_versal_cips_0_3/bd_0/ip/ip_0/bd_98bc_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_98bc_pspmc_0_0 || ORIG_REF_NAME==bd_98bc_pspmc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_versal_cips_0_3/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_98bc_pspmc_0_0 || ORIG_REF_NAME==bd_98bc_pspmc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/ip/Ajit_vck190_versal_cips_0_3/bd_0/bd_98bc_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ip_repo1/src/ajitip/ajitip.gen/sources_1/bd/Ajit_vck190/Ajit_vck190_ooc.xdc
