# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.runs/design_1_fpga_top_0_0_synth_1/design_1_fpga_top_0_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "design_1_fpga_top_0_0_synth_1" START { ROLLUP_AUTO }
set_param chipscope.flow 0
set_msg_config -id {HDL-1065} -limit 10000
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
set_param ips.modRefOverrideMrefDirPath /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/mref
create_project -in_memory -part xcvc1902-vsva2197-2MP-e-S

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vck190:part0:3.2 [current_project]
update_ip_catalog
set_property ip_output_repo /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/common/nsln/nocattrs.dat
read_verilog -library xil_defaultlib -sv {
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/fpu_sp_add.sv
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/fpu_sp_comp.sv
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/fpu_sp_div.sv
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/fpu_sp_mul.sv
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/fpu_sp_sub.sv
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/fpu_top1.sv
}
read_verilog -library xil_defaultlib /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/acceleratorNew1.v
read_vhdl -library xil_defaultlib {
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/aHiR_ieee_proposed.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/ahir.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/simpleUartLib.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/icache.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/dcache.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/AjitCustom.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/SpiMasterLib.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/GenericCoreAddOnLib.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/AhbApbLib.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/GenericGlueStuff.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/GlueModules.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/afb_performance_counters_base.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/afb_performance_counters_controller_1x1.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/afb_performance_counters_1x1.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/ccu.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/debug_interface.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/idecode_idispatch.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/ifetch.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/dummy_fpunit.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/iu_exec.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/iu_writeback_in_mux.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/iu_registers.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/iunit.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/loadstore.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/iretire.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/stream_corrector.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/teu_no_fp.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/cpu_no_fp.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/dummy_mmu.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/mmu_mux.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/munit_no_mmu.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/core_1x32_no_fp_no_mmu.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/simpleI2CLib.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/myUartLib.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/mcore_1x1x32_lite.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/peripherals.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/processor_1x1x32_lite.vhdl
  /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/imports/ajit-ip/fpga_top_with_accelerator.vhdl
}
read_ip -quiet /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/ip/clk_wizard_0/clk_wizard_0.xci
set_property used_in_implementation false [get_files -all /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/ip/clk_wizard_0/clk_wizard_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/ip/clk_wizard_0/clk_wizard_0.xdc]
set_property used_in_implementation false [get_files -all /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/ip/clk_wizard_0/clk_wizard_0_ooc.xdc]

read_ip -quiet /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0.xci
set_property used_in_implementation false [get_files -all /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_fpga_top_0_0 -part xcvc1902-vsva2197-2MP-e-S -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all design_1_fpga_top_0_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_fpga_top_0_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "design_1_fpga_top_0_0_synth_1_synth_report_utilization_0" "report_utilization -file design_1_fpga_top_0_0_utilization_synth.rpt -pb design_1_fpga_top_0_0_utilization_synth.pb"
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.runs/design_1_fpga_top_0_0_synth_1/design_1_fpga_top_0_0.dcp /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.ip_user_files/ip/design_1_fpga_top_0_0]} {
  catch { 
    file copy -force /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0_stub.v /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.ip_user_files/ip/design_1_fpga_top_0_0
  }
}

if {[file isdir /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.ip_user_files/ip/design_1_fpga_top_0_0]} {
  catch { 
    file copy -force /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0_stub.vhdl /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.ip_user_files/ip/design_1_fpga_top_0_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "design_1_fpga_top_0_0_synth_1" END { }
