# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0.xci
# IP: The module: 'design_1_fpga_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/ip/clk_wizard_0/clk_wizard_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wizard_0 || ORIG_REF_NAME==clk_wizard_0} -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/ip/clk_wizard_0/clk_wizard_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wizard_0 || ORIG_REF_NAME==clk_wizard_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/ip/clk_wizard_0/clk_wizard_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wizard_0 || ORIG_REF_NAME==clk_wizard_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/ip/clk_wizard_0/clk_wizard_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fpga_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0.xci
# IP: The module: 'design_1_fpga_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.srcs/sources_1/ip/clk_wizard_0/clk_wizard_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wizard_0 || ORIG_REF_NAME==clk_wizard_0} -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/ip/clk_wizard_0/clk_wizard_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wizard_0 || ORIG_REF_NAME==clk_wizard_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/ip/clk_wizard_0/clk_wizard_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wizard_0 || ORIG_REF_NAME==clk_wizard_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/ip/clk_wizard_0/clk_wizard_0_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/ajit-ip/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_fpga_top_0_0/design_1_fpga_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fpga_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
