# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/constraints/constraints.xdc

# Block Designs: bd/ajitVCK/ajitVCK.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ajitVCK || ORIG_REF_NAME==ajitVCK} -quiet] -quiet

# IP: bd/ajitVCK/ip/ajitVCK_fpga_top_0_1/ajitVCK_fpga_top_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ajitVCK_fpga_top_0_1 || ORIG_REF_NAME==ajitVCK_fpga_top_0_1} -quiet] -quiet

# IP: bd/ajitVCK/ip/ajitVCK_versal_cips_0_12/ajitVCK_versal_cips_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ajitVCK_versal_cips_0_12 || ORIG_REF_NAME==ajitVCK_versal_cips_0_12} -quiet] -quiet

# Block Designs: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/vivado_synth/project_1/project_1.gen/sources_1/bd/ajitVCK/ip/ajitVCK_versal_cips_0_12/bd_0/bd_2ba7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2ba7 || ORIG_REF_NAME==bd_2ba7} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/vivado_synth/project_1/project_1.gen/sources_1/bd/ajitVCK/ip/ajitVCK_versal_cips_0_12/bd_0/ip/ip_0/bd_2ba7_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_2ba7_pspmc_0_0 || ORIG_REF_NAME==bd_2ba7_pspmc_0_0} -quiet] -quiet

# IP: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/vivado_synth/project_1/project_1.gen/sources_1/bd/ajitVCK/ip/ajitVCK_versal_cips_0_12/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/vivado_synth/project_1/project_1.gen/sources_1/bd/ajitVCK/ip/ajitVCK_versal_cips_0_12/bd_0/ip/ip_0/bd_2ba7_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2ba7_pspmc_0_0 || ORIG_REF_NAME==bd_2ba7_pspmc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/vivado_synth/project_1/project_1.gen/sources_1/bd/ajitVCK/ip/ajitVCK_versal_cips_0_12/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_2ba7_pspmc_0_0 || ORIG_REF_NAME==bd_2ba7_pspmc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/vivado_synth/project_1/project_1.gen/sources_1/bd/ajitVCK/ip/ajitVCK_versal_cips_0_12/bd_0/bd_2ba7_ooc.xdc

# XDC: /home/iitg/Desktop/AjitIITG/AjitIITG/1x1x32.iitg/vck190/vivado_synth/project_1/project_1.gen/sources_1/bd/ajitVCK/ajitVCK_ooc.xdc
